name: weather-forecast-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.18.0  # Thay bằng phiên bản bạn dùng trên Colab
  - pandas=2.2.2       # Thay bằng phiên bản bạn dùng trên Colab
  - numpy=2.0.2       # Thay bằng phiên bản bạn dùng trên Colab
  - scikit-learn=1.6.1 # Thay bằng phiên bản bạn dùng trên Colab
  - matplotlib=3.10.0   # Thay bằng phiên bản bạn dùng trên Colab
  - fastapi
  - uvicorn
  - python-multipart